name: Create Archive
on: 
  push:
    branches:
      - release
# This is a comment, and this is used to force a run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: 8
          format: "YYYYMMDDHHmmss"
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: "cnet.smp.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig .github"

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ZBljyxXU
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          #github-tag: 0.{{ github.run_number }}
          #github-generate-changelog: true
          #github-draft: false
          #github-prerelease: false
          #github-commitish: main
          #github-discussion: Announcements
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: |
            ./cnet.smp.zip

          name: Empires.RP-0.${{ github.run_number }}
          version: v.0.${{ github.run_number }}
          version-type: release


          project_type: resourcepack

          game-versions: |
            [1.20,1.20.4)

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
